### PR TITLE
fix infinite unclaimed devices reconnects

### LINKED ISSUE #28: infinite reconnects if divice's ownerID: null
there is a bug..if in device attributes there's no ownerID or its `null` the device reconnects to  the server infinitely

### PR DESCRIPTION
**Pull request by AntonPuko**
Closes #28

### CODE REVIEW

File: src/server/DeviceServer.js [hunk 1]
```diff
@@ -358,7 +358,11 @@ class DeviceServer {
         await this._deviceAttributeRepository.getById(deviceID);
 
       if (!deviceAttributes || !deviceAttributes.ownerID) {
-        device.sendReply('SubscribeFail', message.getId());
+        // not sure if sending 'ok subscribe reply' right in this case, but with
+        // SubscribeFail the device reconnects to the cloud infinitely
+        device.sendReply('SubscribeAck', message.getId());
+        logger.log(`device with ID ${deviceID} wasn't subscribed to` +
+        `${messageName} MY_DEVICES event: the device is unclaimed.`);
```
Comment (jlkalberer) [inline src/server/DeviceServer.js]: nit: it's good to keep these under 80 characters but format like this 
```
logger.log(
  `device with ID ${deviceID} wasn't subscribed to` +
  `${messageName} MY_DEVICES event: the device is unclaimed.`,
);
```

**Review by jlkalberer — APPROVED** [review]

File: src/server/DeviceServer.js [hunk 2]
```diff
@@ -358,7 +358,13 @@ class DeviceServer {
         await this._deviceAttributeRepository.getById(deviceID);
 
       if (!deviceAttributes || !deviceAttributes.ownerID) {
-        device.sendReply('SubscribeFail', message.getId());
+        // not sure if sending 'ok subscribe reply' right in this case, but with
+        // SubscribeFail the device reconnects to the cloud infinitely
+        device.sendReply('SubscribeAck', message.getId());
+        logger.log(
+          `device with ID ${deviceID} wasn't subscribed to` +
+        `${messageName} MY_DEVICES event: the device is unclaimed.`
```
Comment (jlkalberer) [inline src/server/DeviceServer.js:366]: This still isn't 100% correct. You're missing a tab on line 366 and a comma at the end.  I'm going to merge but fix this next time you're looking at this code.

**Review by jlkalberer — APPROVED** [review]
